# Generated by Django 5.2 on 2025-10-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
