# Generated by Django 5.2 on 2025-10-13 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_code',
            field=models.CharField(default='TEMP_CODE', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='EmissionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateTimeField()),
                ('scope3_emissions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('notes', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_entries', to='core.supplier')),
            ],
        ),
    ]
