# Generated by Django 5.2.9 on 2025-12-17 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_supplier_active_supplier_supplier_code_emissionentry'),
        ('saas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionentry',
            name='blockchain_hash',
            field=models.CharField(blank=True, help_text='Blockchain verification hash', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emissionentry',
            name='blockchain_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emissionentry',
            name='data_source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('iot', 'IoT Device'), ('ml_estimate', 'ML Estimate'), ('spend_based', 'Spend-Based Estimate')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='emissionentry',
            name='ml_confidence',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='ML model confidence (0-1)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='annual_spend',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual spend in USD', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='emission_factor',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Emission factor (tCO2e/$)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='saas.tenant'),
        ),
    ]
