# Generated by Django 5.2.9 on 2025-12-17 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_emissionentry_blockchain_hash_and_more'),
        ('saas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scenario_type', models.CharField(choices=[('supplier_switch', 'Supplier Switch'), ('renewable_energy', 'Renewable Energy Adoption'), ('efficiency', 'Energy Efficiency Improvement'), ('transport_optimization', 'Transport Optimization'), ('custom', 'Custom Strategy')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baseline_emissions', models.DecimalField(decimal_places=2, help_text='Baseline emissions in tCO2e', max_digits=12)),
                ('projected_emissions', models.DecimalField(decimal_places=2, help_text='Projected emissions in tCO2e', max_digits=12)),
                ('reduction_percentage', models.DecimalField(decimal_places=2, help_text='Percentage reduction', max_digits=5)),
                ('reduction_amount', models.DecimalField(decimal_places=2, help_text='Absolute reduction in tCO2e', max_digits=12)),
                ('implementation_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost in USD', max_digits=15, null=True)),
                ('payback_period_years', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parameters', models.JSONField(default=dict, help_text='Scenario-specific parameters')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='saas.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_emissions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('projected_emissions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reduction_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('intervention_details', models.TextField(blank=True, help_text='Specific intervention for this supplier')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_suppliers', to='scenarios.scenario')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_participations', to='core.supplier')),
            ],
            options={
                'unique_together': {('scenario', 'supplier')},
            },
        ),
    ]
