# Generated by Django 5.2.9 on 2025-12-17 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_emissionentry_blockchain_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Unique device identifier', max_length=100, unique=True)),
                ('device_name', models.CharField(max_length=255)),
                ('device_type', models.CharField(help_text='e.g., Smart Meter, Energy Monitor, Sensor', max_length=100)),
                ('location', models.CharField(blank=True, help_text='Physical location description', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('installed_date', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('api_key', models.CharField(help_text='API key for device authentication', max_length=255, unique=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iot_devices', to='core.supplier')),
            ],
            options={
                'verbose_name': 'IoT Device',
                'verbose_name_plural': 'IoT Devices',
            },
        ),
        migrations.CreateModel(
            name='IoTReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('energy_kwh', models.DecimalField(decimal_places=4, help_text='Energy consumption in kWh', max_digits=12)),
                ('power_kw', models.DecimalField(blank=True, decimal_places=4, help_text='Instantaneous power in kW', max_digits=10, null=True)),
                ('voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('current', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Temperature in Celsius', max_digits=6, null=True)),
                ('estimated_emissions_kg', models.DecimalField(blank=True, decimal_places=4, help_text='Estimated CO2e in kg', max_digits=10, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional device-specific data')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='iot.iotdevice')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', '-timestamp'], name='iot_iotread_device__c4317a_idx'), models.Index(fields=['-timestamp'], name='iot_iotread_timesta_84a38e_idx')],
            },
        ),
    ]
