# Generated by Django 5.2.9 on 2025-12-17 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_emissionentry_blockchain_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model_type', models.CharField(choices=[('hotspot', 'Hotspot Prediction'), ('spend_estimate', 'Spend-Based Estimation'), ('anomaly', 'Anomaly Detection'), ('forecast', 'Emission Forecasting')], max_length=50)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_path', models.CharField(blank=True, help_text='Path to saved model file', max_length=500)),
                ('accuracy_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('training_data_size', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_emissions', models.DecimalField(decimal_places=2, help_text='Predicted emissions in tCO2e', max_digits=12)),
                ('confidence_score', models.DecimalField(decimal_places=4, help_text='Confidence score (0-1)', max_digits=5)),
                ('is_hotspot', models.BooleanField(default=False, help_text='Flagged as emission hotspot')),
                ('hotspot_reason', models.TextField(blank=True, help_text='Explanation for hotspot classification')),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('period_start', models.DateField(help_text='Start of prediction period')),
                ('period_end', models.DateField(help_text='End of prediction period')),
                ('input_features', models.JSONField(default=dict, help_text='Features used for prediction')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ml_services.mlmodel')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_predictions', to='core.supplier')),
                ('validated_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_predictions', to='core.emissionentry')),
            ],
            options={
                'ordering': ['-prediction_date'],
            },
        ),
        migrations.CreateModel(
            name='SpendBasedEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('spend_amount', models.DecimalField(decimal_places=2, help_text='Spend in USD', max_digits=15)),
                ('emission_factor', models.DecimalField(decimal_places=4, help_text='Emission factor (tCO2e/$)', max_digits=10)),
                ('estimated_emissions', models.DecimalField(decimal_places=2, help_text='Estimated emissions in tCO2e', max_digits=12)),
                ('industry_category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_estimates', to='core.supplier')),
                ('validated_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spend_estimates', to='core.emissionentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
