# Generated by Django 5.2.9 on 2025-12-17 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_emissionentry_blockchain_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(help_text='Blockchain transaction hash', max_length=255, unique=True)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('block_timestamp', models.DateTimeField(blank=True, null=True)),
                ('network', models.CharField(default='ethereum', help_text='Blockchain network (ethereum, polygon, etc.)', max_length=50)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('data_hash', models.CharField(help_text='Hash of the emission data', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('emission_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_verification', to='core.emissionentry')),
            ],
            options={
                'ordering': ['-verified_at'],
            },
        ),
    ]
